settings:
  legacy:
    force: false
    interval: 100ms
server:
  status: false
  open: false
  host: localhost
  port: 5001
schema:
- name: args
  path: .
  commands:
    install:
      status: false
    run:
      status: true
      output: true
      args:      
      - --string="val one"
      - --string1='val two'
      - -string2=val three
      - --bool
      - --int=3

watcher:
  paths:
  - /
  extensions:
  - go
  ignored_paths:
  - vendor
