settings:
  legacy:
    force: true
    interval: 100ms
server:
  status: false
  open: false
  host: localhost
  port: 5001
schema:
- name: coin
  path: .
  commands:
    install:
      status: true
    run: true
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - vendor
