settings:
  files:
    outputs:
      status: false
      name: outputs.log
    logs:
      status: false
      name: logs.log
    errors:
      status: false
      name: errors.log
  legacy:
    force: false
    interval: 100ms
server:
  status: false
  open: false
  host: localhost
  port: 5001
schema:
- name: env
  path: .
  environment:
    var1: test1
    var2: test2
  commands:
    fmt:
      status: true
    install:
      status: true
    run: true
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - vendor
